
var duogeshuzu=[
	[
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:"./images/miphone2.png",
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone3.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone2.png',
			name:'小米MIX2s',
			price:'3299元起',
		}
	],
		[
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:"./images/miphone2.png",
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone3.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone2.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		}
	],
			[
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:"./images/miphone2.png",
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone3.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone2.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		}
	],
			[
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:"./images/miphone2.png",
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone3.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone2.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		}
	],
			[
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:"./images/miphone2.png",
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone3.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone2.png',
			name:'小米MIX2s',
			price:'3299元起',
		},
		{
			img:'./images/miphone1.png',
			name:'小米MIX2s',
			price:'3299元起',
		}
	]
];

var lists=[
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
		],
		[
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list5.jpg',
				name:'小米mix2',
			},
			{
				img:'./images/list1.png',
				name:'小米6x',
			},
			{
				img:'./images/list2.jpg',
				name:'小米mix2s',
			},
			{
				img:'./images/list3.png',
				name:'小米6s',
			},
			{
				img:'./images/list4.png',
				name:'小米6',
			},
			{
				img:'./images/list1.png',
				name:'小米mix2',
			},
		]
];
